Repository ravi230599/expert-eureka, pull requests merged in 2022-10, with the labels that each got.

#4 adding md
  ravi.md
Labels: hacktoberfest-accepted

#5 adding name
  README.md
Labels: hacktoberfest-accepted

#6 ksorted list
  mergeKsortedList.py
Labels: hacktoberfest-accepted

#8 adding name heading
  README.md
Labels: hacktoberfest-accepted

#9 add two numbers list
  addTwoNumbers.py
Labels: hacktoberfest, hacktoberfest-accepted

#10 adding name
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 Create ashutosh.md
  ashutosh.md
Labels: hacktoberfest, hacktoberfest-accepted

#13 Update ashutosh.md
  ashutosh.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 Update ashutosh.md
  ashutosh.md
Labels: hacktoberfest, hacktoberfest-accepted

#14 sorted rotated array
  searchRotatedSortArray.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#12 merge two sorted array
  twoSortedArray.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#17 reverse list
  reverseList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#16 validate
  addTwoNumbers.py
  valid-parenthesis.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#22 Create exponentialSearch.cpp
  exponentialSearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create interpolationSearch.cpp
  interpolationSearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Create jumpSearch.cpp
  jumpSearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create binarySearch.cpp
  binarySearch.cpp
Labels: bug, hacktoberfest, hacktoberfest-accepted

#18 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
